name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          host: windows
          target: desktop
          arch: win64_msvc2019_64
          modules: 'qtcharts qtwebsockets'

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build
        run: cmake --build build --parallel --config RelWithDebInfo

      - name: Test
        working-directory: build
        run: ctest --output-on-failure --build-config RelWithDebInfo
